### ISSUE TITLE
Can't tick international boulders

### ISSUE THREAD

**Issue by emilyg1709** [OpenBeta/open-tacos#1165] opened 2024-07-15 23:29 UTC
## Steps to Reproduce

1. Go to any boulder in international area (screenshot uses The Mantis V4 in Squamish
2. Attempt to tick
3. Error message states cannot retrieve grade of climb

## Screenshots
![error](https://github.com/user-attachments/assets/0839d8e6-0fa6-4768-9c55-7fc3ea6dfe3b)

## Expected Behavior
Should tick like any other climb

## Current Behavior
Does not tick, gives grade retrieval error message shown in screenshot

## Browser & version
Chrome

## Operating system
Windows

**Comment by julianlam** [comment] 2024-08-11 22:50
I'm not certain if this is related to #1130 or not but either way it's causing OpenBeta to be harder to use for international users.

Basically I can't tick anything until this gets looked at.. I might dive into the codebase to see if it's something I can fix, but may not be able to repro.

**Comment by musoke** [comment] 2024-10-21 20:02
Is the conclusion that this is actually a problem with ticking climbs that have recent edits?

**Comment by julianlam** [comment] 2024-10-21 20:06
@daneashman's comment here seemed pertinent:
> From querying other climbs that do not have this error (e.g. Levitate in Smith Rock - also shown below), I noticed that both the data.yds and data.grades.yds were populated.

The affected routes have `data.yds` as `null`. The tick modal uses `data.yds`. It seems to be a leftover artifact from a refactor. `data.yds` could be the "old" way of storing a grade.

**Comment by musoke** [comment] 2024-10-21 20:10
How do people feel about me closing this as a duplicate of #1130 ?  This issue was created earlier, but #1130 seems to have more relevant information.

**Closed as completed** 2024-10-22 16:40 UTC
Labels: bug, duplicate, P1, Component: Log Book
