### ISSUE TITLE
Importing Ticks/Ticks Testing

### ISSUE THREAD

**Issue by Downster** [OpenBeta/open-tacos#525] opened 2022-09-06 16:25 UTC
Hey there guys. I have recently added a feature that allows you to import ticks from mountain project, and tick your own climbs. All of this information should persist in our staging GraphQL database, so if you are interested in testing it out slide on over to [https://graphiql-online.com/](url) and put in the staging endpoint [https://stg-api.openbeta.io](url). Below I am going to list what I think should happen when using this feature, and what is to be expected from it in the future.

- If you have not imported your ticks from Mtn Project, and have not clicked the 'Don't show again' button, you should be met with this notification when visiting a climb.
 ![Screen Shot 2022-09-06 at 9 08 47 AM](https://user-images.githubusercontent.com/24400646/188686016-2518a0f4-00e3-4432-b301-d9df28ceaeb4.png)

- When you click show me how on the notification it should change to an input field which will only take a link in the form of a mountain project profile URL ex: https://www.mountainproject.com/user/200381859/brendan-downing
 
![Screen Shot 2022-09-06 at 9 09 00 AM](https://user-images.githubusercontent.com/24400646/188686372-6701f727-b731-48fc-8d77-c9f304459e90.png)

- After you submit your URL the modal should disappear and not show up again unless you change the ticksImported flag in the UserMetaData to false.
![Screen Shot 2022-09-06 at 9 10 31 AM](https://user-images.githubusercontent.com/24400646/188686622-4c8a5c96-7247-4070-b870-cd1397a263d1.png)

- You should be able to tick a climb by clicking the tick this climb button, have a modal pop up, and see that information persist in the staging database
![Screen Shot 2022-09-06 at 9 11 06 AM](https://user-images.githubusercontent.com/24400646/188687658-e9b48876-6016-434b-b9b5-385869626535.png)

- Once you tick a climb, the button should say 'View Ticks' which will lead you nowhere currently.
![Screen Shot 2022-09-06 at 9 11 34 AM](https://user-images.githubusercontent.com/24400646/188686753-11deaf06-a849-4860-bfbb-6db70d18d814.png)

- If you query the staging database by userID or userID and climbId, you should be able to see the respective ticks
![Screen Shot 2022-09-06 at 9 14 06 AM](https://user-images.githubusercontent.com/24400646/188686911-e4877836-46c2-4b55-822a-ddb6b5aca5d2.png)

- If you run into any bugs, or have any suggestions for improvement please leave a comment here or message me on discord. In the coming weeks, I plan to add a standalone ticks page with some data visualizations that can be accessed through the user profile, and from a climb page if you have ticked that climb previously.

**Comment by vnugent** [comment] 2022-09-07 06:01
1.  Is the import button available in my profile page?  I dismiss it and now can't seem to find it.
2. Is there a way to view my ticks without using the GQL explorer?

**Comment by DarrenZLew** [comment] 2022-09-07 06:31
1. Can you currently only have a single tick for a climb? MP allows multiple ticks of the same climb if you would like. i.e. you add a tick for a climb done on different days.
![image](https://user-images.githubusercontent.com/26758226/188805227-6a4ebcc5-840e-44b0-ae13-b63f2bc94210.png)

**Comment by Downster** [comment] 2022-09-07 17:02
> 1. Is the import button available in my profile page?  I dismiss it and now can't seem to find it.
> 2. Is there a way to view my ticks without using the GQL explorer?

I did not add a button to the profile pages, and yes the ticks will be viewable once I finish the standalone ticks page. I will add a button to the profile page so we can get the modal back. I spaced on that.  Adding the button to get the notification back, and a way to view individual ticks right now.

**Comment by Downster** [comment] 2022-09-07 17:03
> 1. Can you currently only have a single tick for a climb? MP allows multiple ticks of the same climb if you would like. i.e. you add a tick for a climb done on different days.
>    ![image](https://user-images.githubusercontent.com/26758226/188805227-6a4ebcc5-840e-44b0-ae13-b63f2bc94210.png)

Multiple ticks are going to be supported. I will be adding a modal that shows the current ticks of a route and within this modal you will be able to tick it again.

**Comment by Downster** [comment] 2022-10-13 17:16
This feature has been pushed to our "canary branch" you can access it by putting http://stg.openbeta.io/?next=true in the URL

Please mess around with this and let me know of anything you think would be ideal to add or any bugs/improvements you find.

**Comment by vnugent** [comment] 2022-10-13 22:50
I was able to import without any problem.  It'd be nice to have a crude "view my ticks" page to review my ticks.

Filed https://github.com/OpenBeta/open-tacos/issues/576

**Comment by Downster** [comment] 2022-10-14 04:51
> I was able to import without any problem. It'd be nice to have a crude "view my ticks" page to review my ticks.
> 
> Filed #576

I will hop on a view my ticks page in the coming weeks!

**Comment by vnugent** [comment] 2022-10-22 20:17
Filed 
- https://github.com/OpenBeta/open-tacos/issues/578
- https://github.com/OpenBeta/openbeta-graphql/issues/175

**Comment by itsmattsoria** [comment] 2023-04-18 14:03
Not sure if this is the right place to log this, but I'm consistently getting an error when attempting to use the tick import feature for duplicate ticks, something like this: 
```
"E11000 duplicate key error collection: prod-openbeta.ticks index: climbId_1_dateClimbed_1_style_1_userId_1_source_1 dup key: { climbId: "15b29c9d-e00e-5a5b-b3e7-9cb3c65d3ae4", dateClimbed: "2021-01-17", style: "Lead", userId: "c360805f-0aa6-4075-86ae-64c90bd90116", source: "MP" }"
```
Maybe I am just misusing the tick feature on Mountain Project, but apparently I've added a tick for each attempt/lap on routes on the same day, so I have multiple instances of ticks from the same route and same date.

**Comment by musoke** [comment] 2023-04-18 14:10
Thank you for the report @itsmattsoria !  It looks like this is the same issue as https://github.com/OpenBeta/open-tacos/issues/631?  Good to see another data point confirming my hypothesis.

**Comment by vnugent** [comment] 2023-04-18 14:17
I think this is the root cause: https://github.com/OpenBeta/openbeta-graphql/issues/175

**Comment by itsmattsoria** [comment] 2023-04-18 14:21
@musoke sure thing, and yep, my bad.
@vnugent gotcha, thank you! 👍

**Comment by musoke** [comment] 2023-04-18 14:24
Not a problem @itsmattsoria, I'm just happy to see progress

**Comment by vnugent** [comment] 2023-07-21 15:27
@itsmattsoria we recent made a fix to allow multiple ticks of the same climb on the same day (https://github.com/OpenBeta/openbeta-graphql/pull/340).  Can you please try again?

**Comment by itsmattsoria** [comment] 2023-07-21 17:18
@vnugent works like a charm!

**Comment by vnugent** [comment] 2023-07-21 17:23
I'm closing this.  FYI we're now tracking our work on a unified project board: https://github.com/orgs/OpenBeta/projects/8/views/2

If you have ideas or feature requests, please do share by filing a new issue.

**Closed as completed by vnugent** 2023-07-21 17:23 UTC
Labels: help wanted, needs testing, WIP, Component: Log Book
